name: plantf-hpt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=25.0=py39h06a4308_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - affine==2.4.0
      - aioboto3==11.0.1
      - aiobotocore==2.4.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - bokeh==2.4.3
      - boto3==1.24.59
      - botocore==1.27.59
      - cachetools==5.5.1
      - casadi==3.6.7
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - comm==0.2.2
      - contourpy==1.3.0
      - control==0.9.1
      - coverage==7.6.12
      - cryptography==44.0.1
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - distlib==0.3.9
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - fiona==1.10.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - geopandas==1.0.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - grpcio==1.43.0
      - grpcio-tools==1.43.0
      - guppy3==3.1.2
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.0
      - hydra-core==1.3.2
      - hypothesis==6.126.0
      - identify==2.6.7
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lightning-utilities==0.12.0
      - llvmlite==0.43.0
      - markdown==3.7
      - markdown-it-py==2.2.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.2
      - mmengine==0.10.7
      - mock==5.1.0
      - moto==5.0.28
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      # - natten==0.14.6+torch1120cu116
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nodeenv==1.9.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.23.4
      - omegaconf==2.3.0
      - opencv-python==4.5.1.48
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pyarrow==19.0.1
      - pycparser==2.22
      - pygments==2.19.1
      - pyinstrument==5.0.1
      - pyogrio==0.10.0
      - pyparsing==3.2.1
      - pyproj==3.6.1
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==2.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - rasterio==1.3.11
      - ray==2.42.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - responses==0.25.6
      - retry==0.9.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.4
      - rpds-py==0.22.3
      - rtree==1.3.0
      - s3fs==2023.3.0
      - s3transfer==0.6.2
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - selenium==4.28.1
      - send2trash==1.8.3
      - sentry-sdk==2.22.0
      - setproctitle==1.3.4
      - setuptools==59.5.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snuggs==1.4.7
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==1.4.27
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.0.1
      - terminado==0.18.1
      - testbook==0.4.2
      - threadpoolctl==3.5.0
      - timm==1.0.14
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==1.12.0+cu116
      - torchaudio==0.12.0+cu116
      - torchmetrics==0.10.2
      - torchvision==0.13.0+cu116
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trio==0.29.0
      - trio-websocket==0.12.1
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - virtualenv==20.29.2
      - wandb==0.14.2
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xmltodict==0.14.2
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /data/ustc/anaconda3/envs/plantf-hpt
